pipeline {
    agent any
    
    environment {
        UAT_REPO = ${Dest_Repo}
        IQ_APPPLICATION = ${iqAppID}
        IQ_APPPLICATION_ID = sh `curl --silent -u admin:admin123 -X GET http://${IQServer}/api/v2/applications | grep -i ${iqAppID} -B 1 | egrep id | sed 's/         "id" : "//' | sed 's/",//'`
        PROMOTE_DATA_FILE = './promote-data.json'
    }

    stages {
        stage ('Promote components to UAT') {
            steps {
                script {
                    
                    // construct the meta data (Pipeline Utility Steps plugin)
                    def promoteData = readJSON text: '{}' 
                    promoteData.sourceStageId = "build" as String
                    promoteData.targetStageId = "stage-release" as String
                    
                    writeJSON(file: "${PROMOTE_DATA_FILE}", json: promoteData, pretty: 4)
                    sh 'cat ${PROMOTE_DATA_FILE}'                    
                    
                    sh "curl -u admin:admin123 -X POST -H 'Content-Type: application/json' -d  @${PROMOTE_DATA_FILE} http://${IQServer}/api/v2/evaluation/applications/${IQ_APPPLICATION_ID}/promoteScan"
                }
            }
            post {
                success {
                    echo 'Now moving components to UAT repository...'
                    moveComponents destination: "${UAT_REPO}", nexusInstanceId: 'nexus', tagName: "${TAG}"
                    sh "/bin/rm ${PROMOTE_DATA_FILE}"
                }
            }
        }
    }
}
